### ISSUE TITLE
SDL causes memory increasing

### ISSUE THREAD

**Issue by phamanhtuan** [yuvalk/demoLive555withFFMPEG#1]
Hi, 
Thank for sharing your code.
It seems that memory goes up when using SDL
It turns out when you allocate 
struct SwsContext *sws;
                sws = sws_getContext(
                            c->width,
                            c->height,
                            PIX_FMT_YUV420P,
                            c->width,
                            c->height,
                            PIX_FMT_YUV420P,
                            SWS_BICUBIC,
                            NULL,
                            NULL,
                            NULL
                            );
sws is not freed after displaying.

I free it by using sws_freeContext(sws); and it worked.

By the way, can you please show me how to change rtsp stream url and play that stream again?

Thank you in advance!!!

**Comment by yuvalk** [comment]
fixed.

this example code get the url from cli, just pass it a different url and it will play it..
actually you can even pass more than one url and it will play them by order.

please note though, that this example uses hardcoded width/height values (instead of reading it from the stream)
